language: generic
sudo: false

os:
  - linux
  - osx

env:
  global:
    - MINICONDA_DIR="$HOME/miniconda"
  matrix:
    - Python=3.5
    - Python=3.6

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      export CONDA_OS_NAME="MacOSX";
    else
      export CONDA_OS_NAME="Linux";
    fi;
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-${CONDA_OS_NAME}-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $MINICONDA_DIR
  - export PATH="$MINICONDA_DIR/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - sed -i -e "s/python=3/python=$Python/" environment.yml;

install:
  - if [[ $Task != 'website' ]]; then
      conda env create -q -f environment.yml;
      source activate gallery;
      conda list;
    fi

script:
  - cd website
  - make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: website/build/html
  target_branch: gh-pages
  on:
    branch: master
    python: 3.6
