# Since we really don't want any of Travis' Python
language: generic
sudo: false

python:
env:
  global:
    - MINICONDA_DIR="$HOME/miniconda"
    - GH_PAGES_DIR="$HOME/site_build/"
  matrix:
    - Python=3.4
    - Python=3.5

matrix:
  include:
    - language: ruby
      rvm: 2.2
      env: Task=website

before_install:
  - if [[ $Task == 'website' ]]; then
      gem install github-pages jekyll-org-mode-converter;
      pip install --user linkchecker pyopenssl ndg-httpsclient pyasn1 "requests<=2.9";
      pip install --user nbconvert;
    else
      deactivate;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $MINICONDA_DIR;
      export PATH="$MINICONDA_DIR/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda update -q conda;
      conda info -a;
      sed -i -e "s/python=3/python=$Python/" environment.yml;
    fi;

install:
  - if [[ $Task != 'website' ]]; then
      conda env create -f environment.yml;
      source activate gallery;
      python --version;
      python -m ipykernel install --user --name gallery;
      conda list;
    fi

script:
  - if [[ $Task == 'website' ]]; then
      python nbconverter.py;
      jekyll build -s website -d $GH_PAGES_DIR 2>build.log;
      if [ -s build.log ]; then
          echo Build produced errors:;
          cat build.log;
          false;
      else
        echo Checking links;
        echo linkchecker --anchors --ignore mybinder --check-extern $GH_PAGES_DIR;
      fi;
    else
      find notebooks/ -name \*.ipynb -print0 | xargs -0 -n1 jupyter nbconvert --execute --ExecutePreprocessor.timeout=180 --ExecutePreprocessor.kernel_name=gallery --to=notebook --stdout >| /dev/null;
    fi

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
    condition: $Task == 'website'
