 name: gallery
 channels:
   - conda-forge
 dependencies:
   - python=3
   - numpy=1.11
   - matplotlib!=2.1
   - cartopy
   - jupyter
   - metpy
   - siphon
   - sphinx!=1.6.4
   - sphinx-gallery
   - sphinx_rtd_theme
   - xarray
