 name: unidata-blog
 channels:
   - https://conda.binstar.org/scitools
   - https://conda.binstar.org/Unidata
 dependencies:
   - python=3.4
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - netcdf4
   - metpy
   - siphon

