 name: unidata-blog
 channels:
   - https://conda.binstar.org/conda-forge
   - https://conda.binstar.org/scitools
 dependencies:
   - python=3
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - metpy
   - siphon

